# Generated by Django 5.1.1 on 2025-05-14 15:45

import sentry.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sentry", "0002_template_analysis_changes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysis",
            name="cost_estimate",
            field=models.JSONField(validators=[sentry.models.validate_cost_estimate]),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="security_issues",
            field=models.JSONField(validators=[sentry.models.validate_security_issues]),
        ),
        migrations.AlterField(
            model_name="analysis",
            name="validation_results",
            field=models.JSONField(
                validators=[sentry.models.validate_validation_results]
            ),
        ),
    ]
